name: R-Tunes Daily Voice Bot

on:
  schedule:
    - cron: '30 3 * * *'  # Runs every day at 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch:       # Allow manual trigger

jobs:
  send-voice:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run bot script
        run: node sendDaily.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
